### PR TITLE
Fix to sklearn2json

### PR DESCRIPTION
**Pull request by demarley**
Corrected converter (`sklearn2json`) and updates JSON files for testing.

### CODE REVIEW

**Comment by demarley** [comment]
I got things to agree locally in my python setup.  Now I'm going to compare with the `lwtnn` output.  When we have both validated the changes we can merge.

**Comment by demarley** [comment]
Also, it appears that for the `StandardScaler` object, 
`sqrt(scaler.var_) == scaler.scale_`.
I will update the code to remove the `sqrt` calls.

**Comment by demarley** [comment]
Okay, I think everything is ready to merge.  
Let me know if there are any questions/problems!

**Comment by justinrpilot** [comment]
Reclustering of jets in boosted frames needs the sorted_by_pt() method added.

**Comment by demarley** [comment]
Okay, this has all been updated.  
The only issue now is that the `lwtnn` output doesn't agree with the `scikit-learn` output well-enough (1e-6) enough to pass all tests.  The agreement is at 1e-4/1e-5 right now (though there _could_ be examples with less agreement, I suppose).  
That issue is being addressed in the `lwtnn` package.  For now, the precision is fine for using in analysis, I believe.

**Comment by demarley** [comment]
Feel free to remove the `*.pkl` and `TMVA` files from the `BoostedEventShapeTagger/data/` directory as well.

**Pull request merged**
